# tasks/artifacts.yml
# Main artifact phase.
#

- name: Artifacts | main phase
  ansible.builtin.import_tasks: artifacts_apply.yml
  vars:
    artifacts_active: "{{ artifacts_merged | default([], true) }}"
