---
- name: Restart NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager
    state: restarted

- name: Restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted

- name: Restart Postfix
  ansible.builtin.systemd:
    name: postfix
    state: restarted

- name: Restart sssd
  ansible.builtin.systemd:
    name: sssd
    state: restarted

- name: Restart httpd
  ansible.builtin.systemd:
    name: httpd
    state: restarted

- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted

- name: Restart autofs
  ansible.builtin.systemd:
    name: autofs
    state: restarted

- name: Restart crond
  ansible.builtin.systemd:
    name: crond
    state: restarted

- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: Update CA Trust
  ansible.builtin.command:
    cmd: update-ca-trust
  check_mode: false
  changed_when: true

- name: Systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  listen: "systemd daemon-reload"

- name: Reload firewalld
  ansible.builtin.command: firewall-cmd --reload
  changed_when: true

- name: Reload NFS exports
  ansible.builtin.command: exportfs -ra
  changed_when: true
